services:
  nestjs-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'

  #  environment:
  #     - ENV MYSQL_ROOT_PASSWORD=randomrootpassword
  #     - ENV MYSQL_DATABASE=nestjs_typeorm
  #     - ENV MYSQL_USER=root
  #     - ENV MYSQL_PASSWORD=randomrootpassword
  #     - MYSQL_TCP_PORT=3306
  #     - MYSQL_PORT=3306
  #     - MYSQL_SYNCHRONIZE=true

#docker-compose up --build