FROM node:20

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

RUN rm -rf ./src

EXPOSE 3001

CMD [ "npm", "run", "start:prod" ]

## Create a docker image
## docker build -t nest-prod -f Dockerfile.prod . 

## RUN the build to form a container
## docker run -p 8000:3000 nest-prod 